version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=267844006800.dkr.ecr.eu-west-1.amazonaws.com/sysinfo/base
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Perform test on commit ${COMMIT_HASH}
      - echo Run tests...
      - mkdir ./dist && pwd && ls -la
      - docker run -i -v `pwd`/dist:/app/dist $REPOSITORY_URI:latest
        bash -c "setup.py bdist_wheel"
  post_build:
    commands:
      - echo Production package $COMMIT_HASH on `date`
      - echo Packing artifacts...
      - ls -la ./dist
artifacts:
  files:
    - ./dist/*